name: Nuclear Event Alert System

on:
  #schedule:
  #  - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows for manual trigger
    inputs:
      simulate_lat:
        description: 'Latitude for simulation'
        required: false
        default: ''
      simulate_lon:
        description: 'Longitude for simulation'
        required: false
        default: ''
      simulate_radiation:
        description: 'Simulated radiation level'
        required: false
        default: ''

jobs:
  monitor-events:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Monitor USGS and Safecast
      run: |
        python check_nuclear_events.py \
          --simulate-lat ${{ inputs.simulate_lat }} \
          --simulate-lon ${{ inputs.simulate_lon }} \
          --simulate-radiation ${{ inputs.simulate_radiation }}
