name: Nuclear Event Alert System

on:
  #schedule:
  #  - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows for manual trigger
    inputs:
      simulate_lat:
        description: 'Latitude for simulation'
        required: false
        default: ''
      simulate_lon:
        description: 'Longitude for simulation'
        required: false
        default: ''
      simulate_radiation:
        description: 'Simulated radiation level'
        required: false
        default: ''

jobs:
  monitor-events:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Build and Run Monitoring Command
      env:
        BLUESKY_CLOSET_H: ${{ secrets.BLUESKY_CLOSET_H }}
        BLUESKY_CLOSET_P: ${{ secrets.BLUESKY_CLOSET_P }}
      run: |
        CMD="python src/check_nuclear_events.py"
        if [ -n "${{ inputs.simulate_lat }}" ]; then
          CMD="$CMD --simulate-lat ${{ inputs.simulate_lat }}"
        fi
        if [ -n "${{ inputs.simulate_lon }}" ]; then
          CMD="$CMD --simulate-lon ${{ inputs.simulate_lon }}"
        fi
        if [ -n "${{ inputs.simulate_radiation }}" ]; then
          CMD="$CMD --simulate-radiation ${{ inputs.simulate_radiation }}"
        fi
        echo "Running: $CMD"
        eval $CMD
