name: Nuclear Event Alert System

on:
  #schedule:
  #  - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows for manual trigger
    inputs:
      simulate_lat:
        description: 'Latitude for simulation'
        required: false
        default: ''
      simulate_lon:
        description: 'Longitude for simulation'
        required: false
        default: ''
      simulate_radiation:
        description: 'Simulated radiation level'
        required: false
        default: ''

jobs:
  monitor-events:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Build command for monitoring
      id: build_command
      run: |
        CMD="python src/check_nuclear_events.py"
        if [ "${{ inputs.simulate_lat }}" != "" ]; then
          CMD="$CMD --simulate-lat ${{ inputs.simulate_lat }}"
        fi
        if [ "${{ inputs.simulate_lon }}" != "" ]; then
          CMD="$CMD --simulate-lon ${{ inputs.simulate_lon }}"
        fi
        if [ "${{ inputs.simulate_radiation }}" != "" ]; then
          CMD="$CMD --simulate-radiation ${{ inputs.simulate_radiation }}"
        fi
        echo "command=$CMD" >> $GITHUB_ENV

    - name: Run Monitoring Command
      run: ${{ env.command }}
